### PR TITLE
release/1.2.0

### PR DESCRIPTION
**Pull request by ArshaanNazir**
release/1.2.0

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ArshaanNazir** [comment]
@conda-forge-admin, please rerender

**Comment by luca-martial** [comment]
Hey @sugatoray ! Our latest release build failed for conda forge. The PyPI package uses a dependency (rouge_score) which we had to exclude from the conda recipe since it's not available in conda. 

Here is the failed build error: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=704731&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=1111

This is the error that pops up in there:
```
import: 'nlptest'
import: 'nlptest'
+ pip check
nlptest 1.2.0 requires rouge-score, which is not installed.
Tests failed for nlptest-1.2.0-pyhd8ed1ab_0.conda - moving package to /home/conda/feedstock_root/build_artifacts/broken
WARNING:conda_build.build:Tests failed for nlptest-1.2.0-pyhd8ed1ab_0.conda - moving package to /home/conda/feedstock_root/build_artifacts/broken
TESTS FAILED: nlptest-1.2.0-pyhd8ed1ab_0.conda
```

Any idea how we should resolve this? We're getting the same error locally

**Comment by xhochy** [comment]
Please add that dependency to conda-forge. That's the sole way forward.

**Comment by sugatoray** [comment]
Hi @xhochy,

Thank you. I have started the packaging of `rouge-score`. If you could review once the build completes, it will be very kind of you.

- https://github.com/conda-forge/staged-recipes/pull/22810  

cc: @ArshaanNazir @luca-martial

**Comment by xhochy** [comment]
Merged, should be available in 1-2h on the index.

**Comment by sugatoray** [comment]
@conda-forge-admin, please rerender

**Comment by sugatoray** [comment]
@conda-forge-admin, please restart ci

source: [see here](https://conda-forge.org/docs/maintainer/infrastructure.html#conda-forge-admin-please-restart-ci)

**Comment by sugatoray** [comment]
@conda-forge-admin, please restart ci

**Comment by sugatoray** [comment]
## Possible Options

This is the error now. [(error)](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=705254&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=679)

```sh
import: 'nlptest'
import: 'nlptest'
+ pip check
nlptest 1.2.0 requires rouge-score, which is not installed.
Tests failed for nlptest-1.2.0-pyhd8ed1ab_0.conda - moving package to /home/conda/feedstock_root/build_artifacts/broken
WARNING:conda_build.build:Tests failed for nlptest-1.2.0-pyhd8ed1ab_0.conda - moving package to /home/conda/feedstock_root/build_artifacts/broken
TESTS FAILED: nlptest-1.2.0-pyhd8ed1ab_0.conda
##[error]Bash exited with code '1'.
```

This package (`rouge-score`) was missing from run:requirements.

> :bell: I have updated the recipe and added `rouge-score`. The new build should work, unless something else is missing.

cc: @luca-martial @ArshaanNazir

**Comment by luca-martial** [comment]
Thank you so much @sugatoray & @xhochy ! 🙏

**Pull request merged**
